---

- name: Install Prometheus, Node Exporter, Alertmanager, cAdvisor, and Grafana on remote server
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - group_vars/all/vault.yml
  tasks:
    - name: Install Node Exporter
      include_role:
        name: prometheus.prometheus.node_exporter

    - name: Install cAdvisor
      include_role:
        name: prometheus.prometheus.cadvisor

    - name: Install Prometheus
      include_role:
        name: prometheus.prometheus.prometheus
    
    - name: Install Alertmanager
      ansible.builtin.package:
        name: alertmanager
        state: present

    - name: Ensure Alertmanager is running
      ansible.builtin.systemd:
        name: alertmanager
        enabled: true
        state: started

    - name: Copy Alertmanager configuration file
      ansible.builtin.template:
        src: alertmanager/alertmanager.yml.j2
        dest: /etc/alertmanager/alertmanager.yml
      notify:
        - Restart Alertmanager

    - name: Install Grafana
      include_role:
        name: grafana.grafana.grafana
      vars:
        grafana_server_port: 3000
        grafana_install_dir: /usr/share/grafana
        grafana_config:
          server:
            root_url: http://localhost:3000
        grafana_security:
            admin_user: "{{ grafana_user }}"
            admin_password: "{{ grafana_password }}"

  handlers:
    - name: Restart Alertmanager
      ansible.builtin.systemd:
        name: alertmanager
        state: restarted

