---

- name: Install Prometheus, Node Exporter, Alertmanager, cAdvisor, and Grafana on remote server
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - group_vars/all/vault.yml
  tasks:
    - name: Install Node Exporter
      include_role:
        name: prometheus.prometheus.node_exporter

    - name: Install cAdvisor
      include_role:
        name: prometheus.prometheus.cadvisor

    - name: Install Prometheus
      include_role:
        name: prometheus.prometheus.prometheus
        vars:
          prometheus_targets:
            - job_name: 'node_exporter'
              static_configs:
                - targets: ['localhost:9100']
            - job_name: 'alertmanager'
              static_configs:
                - targets: ['localhost:9093']

    - name: Install Alertmanager
      include_role:
        name: prometheus.prometheus.alertmanager
        vars:
          alertmanager_receivers:
            - name: 'email'
              email_configs:
                - to: 'it-team@example.com'
                  send_resolved: true

    - name: Restart Prometheus
      service:
        name: prometheus
        state: restarted

    - name: Restart Alertmanager
      service:
        name: alertmanager
        state: restarted

    - name: Install Grafana
      include_role:
        name: grafana.grafana.grafana
      vars:
        grafana_server_port: 3000
        grafana_install_dir: /usr/share/grafana
        grafana_config:
          server:
            root_url: http://localhost:3000
        grafana_security:
            admin_user: "{{ grafana_user }}"
            admin_password: "{{ grafana_password }}"

